### ISSUE TITLE
Chinese garbage problem under fedora39

### ISSUE THREAD

**Issue by KexinCC** [flathub/com.xunlei.Thunder#2]
I've tried installing this app using flatpak and alien deb installer conversion, but without exception they both have this problem, sorry I'm a rookie can't provide more info
![截图 2023-11-21 19-24-12](https://github.com/flathub/com.xunlei.Thunder/assets/59146797/0804e619-d69b-43e3-b55c-0e3573990e20)

**Comment by qvshuo** [comment]
> I've tried installing this app using flatpak and alien deb installer conversion, but without exception they both have this problem, sorry I'm a rookie can't provide more info ![截图 2023-11-21 19-24-12](https://private-user-images.githubusercontent.com/59146797/284563115-0804e619-d69b-43e3-b55c-0e3573990e20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDM1MTQsIm5iZiI6MTcwMTI0MzIxNCwicGF0aCI6Ii81OTE0Njc5Ny8yODQ1NjMxMTUtMDgwNGU2MTktZDY5Yi00M2UzLWI1NWMtMGUzNTczOTkwZTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA3MzMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YjkxNTM4ZjI4NDEwZWM3NmY4YWRmYThiM2NhZDk4MGI5NDRkMWYxNTZiNTEzODk1OTU5ODM0OTRmNDNiNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XHUgsuhcpirgFFn-Jt_2yna6THbGv0dFQDtjdE2pB5Y)

You can try granting the read permission of the font directory to the Flatpak application.

**Comment by KexinCC** [comment]
Thank you for your reply I reinstalled the font and additionally installed other fonts and it is now ready to use!
